blank_issues_enabled: false
contact_links:
  - name: Security issues
    url: https://twitter.com/kabir0x23
    about: For security issues contact us here.

  - name: All Links
    url: https://linktr.ee/kabir0x23
    about: All social Links.

  - name: Discord community
    url: https://discord.gg/WhDry9FWE7
    about: Join our inclusive Discord community.

  - name: "Communities:"

  - name: Discord community
    url: https://discord.gg/WhDry9FWE7
    about: Join our inclusive Discord community.

  - name: CryptoverseWeb3 community
    url: https://linktr.ee/thecyberworld
    about: CryptoverseWeb3 community links.

  - name: Thecyberworld community
    url: https://linktr.ee/thecyberworld
    about: Thecyberworld community links.

