name: Documentation issue
description: Found an issue in the documentation? You can use this one!
title: '[DOCS] <description>'
labels: [Documentation issue]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, I confirm I've read and complied with the [CoC](https://github.com/kabir0x23/Portfolio/blob/main/CODE_OF_CONDUCT.md) 🖖
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: markdown
    attributes:
      value: |
        ---
        If you would like to continue contributing to open source and would like to do it with an awesome inclusive community.
        You should join our [Discord](https://discord.gg/WhDry9FWE7) chat.
        We help and encourage each other to contribute to open source little and often 😄.
        Feel free to check out other cool open-source repositories and communities:
          - [kabir0x23](https://github.com/kabir0x23)
          - [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
          - [Thecyberworld](https://github.com/thecyberworld).
        Any questions let us know.
